import type { PresetDefinition } from './types'

export const PRESETS: PresetDefinition[] = [
  {
    id: 'lofi',
    name: 'Lo-Fi',
    theme: 'void',
    params: {
      playbackRate: 0.78,
      reverbMix: 0.47,
      reverbDecay: 2.5,
      reverbRoomSize: 0.68,
      volume: 0.80,
      eq: { low: 3, mid: -1, high: -5 },
      chorus: { rate: 0, depth: 0 },
      saturationDrive: 0,
      hzFrequency: null,
      pitchSemitones: 0,
    },
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    theme: 'neon',
    params: {
      playbackRate: 0.69,
      reverbMix: 0.74,
      reverbDecay: 3.3,
      reverbRoomSize: 0.52,
      volume: 0.80,
      eq: { low: 1.5, mid: 1, high: 2 },
      chorus: { rate: 0.2, depth: 0 },
      saturationDrive: 0,
      hzFrequency: null,
      pitchSemitones: 0,
    },
  },
  {
    id: 'ambient',
    name: 'Ambient',
    theme: 'mono',
    params: {
      playbackRate: 0.65,
      reverbMix: 0.70,
      reverbDecay: 4.4,
      reverbRoomSize: 0.81,
      volume: 0.75,
      eq: { low: 0, mid: -3, high: -2 },
      chorus: { rate: 0.5, depth: 0.10 },
      saturationDrive: 0,
      hzFrequency: 432,
      pitchSemitones: 0,
    },
  },
  {
    id: 'hyperpop',
    name: 'Hyperpop',
    theme: 'ember',
    params: {
      playbackRate: 1.25,
      reverbMix: 0.27,
      reverbDecay: 1.7,
      reverbRoomSize: 0.59,
      volume: 0.80,
      eq: { low: 1, mid: -3.5, high: 1 },
      chorus: { rate: 0.8, depth: 0.08 },
      saturationDrive: 0.07,
      hzFrequency: null,
      pitchSemitones: 0,
    },
  },
]
